FROM ghcr.io/cyber-dojo-languages/bash:9a88d8f
LABEL maintainer=jon@jaggersoft.com

RUN apk add curl \
 && curl -s https://raw.githubusercontent.com/bash-unit/bash_unit/master/install.sh | bash \
 && apk del curl \
 && mv bash_unit /usr/bin/

COPY red_amber_green.rb /usr/local/bin
