FROM ghcr.io/cyber-dojo-languages/bash:869fdc6
LABEL maintainer=jon@jaggersoft.com

RUN apk add curl \
 && curl -s https://raw.githubusercontent.com/bash-unit/bash_unit/master/install.sh | bash \
 && apk del curl \
 && mv bash_unit /usr/bin/
